name: My Coverity Workflow
# Use this YAML in your workflow file for each job
# Example: https://documentation.blackduck.com/ja-JP/bundle/bridge/page/documentation/c_github-coverity.html
on: 
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  run-on-self-hosted:
    # runs-on: [ ubuntu-latest ]
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Coverity Scan
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          ### SCANNING: Required fields
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          ### Perform local analysis with full toolkit
          coverity_local: true
          ### e.g. /opt/cov-analysis-linux64-2025.6.2 (Don't include "bin")
          #coverity_install_directory: ${{ vars.COVERITY_INSTALL_DIRECTORY }}
          coverity_install_directory: /home/coverity/cov-analysis-linux64-2024.9.1
          ### POLICY ENFORCEMENT: Break build on full scan when encounter oustanding issues
          #coverity_policy_view: ${{ github.event_name != 'pull_request' && 'Outstanding Issues' || '' }}
          ### PULL REQUEST COMMENTS:
          #coverity_prComment_enabled: true
          # Required when PR comments is enabled
          #github_token: ${{ secrets.GITHUB_TOKEN }}
